### ISSUE TITLE
[i9070/CM10.1/N27/08/13] Bug with Instagram : Adv. Instagram Camera

### ISSUE THREAD

**Issue by xpzz** [TeamCanjica/TeamCanjica#1]
There's a bug with instagram the adv camera of instagram appears cuted in half for pictures, but for videos works fine  see attached files 

![screenshot_2013-08-26-16-23-40](https://f.cloud.github.com/assets/308739/1046157/eb597a86-1033-11e3-96b6-7b0edd47ad96.png)

![screenshot_2013-08-26-16-30-56](https://f.cloud.github.com/assets/308739/1046156/eb3b077c-1033-11e3-882c-6ba55b59975c.png)

**Comment by frapeti** [comment]
did you test it on stock rom?

**Comment by xpzz** [comment]
Yes, it works fine with stock rom... also if you take a screenshoot with cm in Screenshoot camera will appear correctly...

**Comment by frapeti** [comment]
it's an app's incompatibility, workaround:

"In instagram's settings uncheck the "Use instagram advanced camera".
underneath it says clearly that the feature might not work on every device. =)
Once unchecked, instagram will use defualt camera app for taking photos."

More info: http://talk.sonymobile.com/t5/Xperia-U/camera-problem-with-instagram-and-path-after-upgrade-to-ICS/td-p/267754

**Comment by xpzz** [comment]
Yes, but if you use internal cam  you can't able to post videos on instagram...   it's a bug of CM because it works on stock rom....  i believe that this issue can be reopened  because it maybe can be fixed with  a small adjusts on camera...  in the forum that you sent people recomend this workaround untill instagram update the fix... but instagram will not make a update for a custom rom....

**Comment by frapeti** [comment]
In that forum they were talking about sony stock rom

**Comment by xpzz** [comment]
@frapeti  just to you know, if we disable  HW Overlays from the Developer Options  camera works fine
