### ISSUE TITLE
WiFi direct / P2P

### ISSUE THREAD

**Issue by frapeti** [TeamCanjica/TeamCanjica#11]
WiFi direct not working

**Comment by frapeti** [comment]
fixed

**Comment by tanmayvg** [comment]
Wifi direct not working 25/09.... It searches devices but does not connect. Also no share via wifi direct option available. Please open this issue if there is no solution as yet.
Upgraded from 10/9 build. In 10/09 it did not even search. In 25/09 it searches but does not connect. Tested with Galaxy Note 2 Stock JB.
