### ISSUE TITLE
WiFi tethering

### ISSUE THREAD

**Issue by frapeti** [TeamCanjica/TeamCanjica#12]
WiFi tethering not working

**Comment by slavosarik** [comment]
phyowaiummg found fully working fix made by PolishVodka -flash this zip file from recovery, it will enable wifi tether on CM 10.1

http://www.mediafire.com/download/9m8oblttnl1dkik/ALL4ROOTBOX_fixes.zip

wifi tether tested by myself, fully working on 101% (there is other fix for gps/volume in call, etc...included in that file, but I didnt test them)

**Comment by frapeti** [comment]
they are prebuilts and we build from source, I think the binary file that makes it possible in that zip file is "netd"

**Comment by slavosarik** [comment]
If you dont have sources, is it still impossible to include these files/folders in /system in future builds? I mean to include them as a normal files, just like a wallpapers, or ring-tones. (Sorry, I dont have experience with building)

**Comment by frapeti** [comment]
sorry, the correct binary file needed is "hostapd", and yes, we can include it as a temp fix, but that's not the idea of this project, we try to build everything from source so other people can use our repos or add their commits to improve this project, this is the first time I see people not sharing sources so it's very sad to the open source comunity

**Comment by RobertRozic** [comment]
https://github.com/Rox-/external_wpa_supplicant_8/commit/d98458c34688b9e9d21a7486e211b926fdf39d8f

try this one guys :) solved wi fi tethering for ace 2 (4.2.2 roms)

**Comment by frapeti** [comment]
Thanks ROX :D implementing it now

**Comment by RobertRozic** [comment]
so it is not working... i dont know why it worked on testing for me... sorry, i will try to find another fix

**Comment by frapeti** [comment]
I didnt have time yet to test it, did it work for you?

**Comment by andrzejressel** [comment]
Hi,
For me (Slimrom and PAC-Rom - Galaxy Ace 2) using older hostapd (from 4.1.2) solves this issue.
