### ISSUE TITLE
Compass not working

### ISSUE THREAD

**Issue by vicodin99** [TeamCanjica/TeamCanjica#14]
When accessing the compass, it doesn't work.

**Comment by xpzz** [comment]
as workaround install https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2 and go to tools > Calibrate compass  and shazam... it will work...

**Comment by vicodin99** [comment]
Done that on 27/08 and it doesn't work. I've read that 30/08 is good to go with the calibration. 

I'll wait for a newer build that has 31/08 possible EFS corruption fixed...

**Comment by Alberto97** [comment]
I'm on 27/08 and for me it works :)

**Comment by xpzz** [comment]
on 12/09 it don't work....
