### ISSUE TITLE
SIM contacts

### ISSUE THREAD

**Issue by slavosarik** [TeamCanjica/TeamCanjica#15]
Cant read/import/export SIM contacts from/to SIMcard. I tried also several apps from Goole Play Store, no success. When I use stock rom, I am able to read/import/export SIM contacts without any problem. Tried various builds, clean install with wipes.

device GT I9070

Log included: https://www.dropbox.com/s/lyn6tumyknb8yid/logcat.log

![screenshot_2013-08-29-18-55-31](https://f.cloud.github.com/assets/5340526/1051506/290ad42c-10cc-11e3-91a2-6f3bae74cf3e.png)

**Comment by xpzz** [comment]
I can able to import contacts from sim without problems...i'm using the last 27/08 nightly

**Comment by slavosarik** [comment]
I tried CM 10 too, no success. It looks like my SIM card contacts are "unsupported" in CM ROMS as I have no issues on stock ROM

**Comment by frapeti** [comment]
I think this is not a rom's issue
