### ISSUE TITLE
GPS stuck on when turning it off

### ISSUE THREAD

**Issue by vicodin99** [TeamCanjica/TeamCanjica#17]
Sometimes when you use the GPS, when turning it off it remains on. How do we know this? Going to the battery stats page in settings, you can see the GPS bar:

http://forum.xda-developers.com/showpost.php?p=45532261&postcount=2329

I have experienced the same in the past, but a phone reboot solves it. What triggers it? No idea.

**Comment by vicodin99** [comment]
Invalid? Someone else experiencing the same issue on the latest nightly

http://forum.xda-developers.com/showpost.php?p=45708627&postcount=2560

**Comment by vicodin99** [comment]
And the same guy found a possible solution 

http://forum.xda-developers.com/showpost.php?p=45730626&postcount=2569

I can say I remember it going away when plugging it to my charger... but it was some time ago since I've had that glitch.

Not invalid, I'd say... it relates to the inaccurate battery graphs I reported on another ticket.

**Comment by frapeti** [comment]
Will be reopened if necessary
