### ISSUE TITLE
[i9070/CM10.1/N27/08/13] Black web videos when you click  full screen

### ISSUE THREAD

**Issue by xpzz** [TeamCanjica/TeamCanjica#2]
When you open a flash video in any website it works fine, but if you click in full screen  you ill see only the player controls and  a black video with sound...

**Comment by frapeti** [comment]
it's not a rom issue, tried several flash videos just to test and they work fine even in fullscreen mode, it isn't related to cm rom also

**Comment by xpzz** [comment]
there's a lot of videos that closes "browser" cuild you test  some videos on www.globo.com/videos  or   tvuol.com.br/videos  ?  i made all wipes and reinstalled a clean rom  and still the same closing browser or  black screen..

Also this are happened with others people in our facebook page about our phone that are testing CM 10.1

**Comment by frapeti** [comment]
try them in stock jb and see what happens, think also that flash player is deprecated now

**Comment by diego-ch** [comment]
Since flash is not officially supported on 4.1+
I don't think this is our issue,,,

2013/9/1 Franco Rapetti notifications@github.com

> try them in stock jb and see what happens, think also that flash player is
> deprecated now
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCanjica/TeamCanjica/issues/2#issuecomment-23631629
> .

## 

Diego Porto
Graduando em Ciência da Computação - UFPB

**Comment by xpzz** [comment]
yes, but works on stock... maybe some fine tunning because video open after a few seconds freeze and only audio works or  close web browser, maybe it can be related with OMX ?

Sorry for bad english...

@diego-ch  o que eu quis dizer é que na stock funciona normal... e na CM será que pode ser algo relacionado aos OMX? pois videos começam a rodar e depois de segundos travam... descobri sem querer quando instalei no cel da minha namorada e ela fica assistindo videos de "a fazenda"  se vc tentar no seu ai http://afazenda.r7.com/a-fazenda-6/videos/integra/  vai ver como está.ai tive que voltar a dela para stock pois todos os videos rodam de boa...  Valeu...

**Comment by xpzz** [comment]
@diego-ch @frapeti   just to you know i found a workaround that can make things more clear... this site that i commented the videos crash web browser.. but if i delete all files in /data/data/com.android.browser and reopen the browser the videos works fine... but after a few minutes the same bug occour...

**Comment by diego-ch** [comment]
Sounds like an issue with cm browser ( chromium ).
Gotta check the logs to see what's going on
Em 03/09/2013 02:37, "xpzz" notifications@github.com escreveu:

**Comment by frapeti** [comment]
I think it's a problem related to cache size I'll see if I can improve it, meanwhile try using dolphin

**Comment by xpzz** [comment]
d=1
I/ADM     (27142): 4: 19326988470: [STATUS] api_devset:615 API LEAVE: Opened new
 device 'Speaker', handle = 101
I/sec_anm_ahi_output(27166): adm_api: opened device. bufsz=3904 num_bufs=3 bufp=
41F0A000
E/        ( 1598): copybit_stretch: blt request failed (Invalid argument)!
E/SurfaceTexture( 1598):
E/SurfaceTexture( 1598): Error: Blit stretch operation failed (err:-1)
E/SurfaceTexture( 1598): updateTexImage: convert failed
E/BufferQueue( 1598): [unnamed-1598-1] acquireBuffer: max acquired buffer count
reached: 2 (max=1)
E/SurfaceTexture( 1598): [unnamed-1598-1] updateTexImage: acquire failed: Functi
on not implemented (-38)

[this message appears a lot of times]

E/SurfaceTexture( 1598): [unnamed-1598-1] updateTexImage: acquire failed: Functi
on not implemented (-38)
I/NuCachedSource2(27166): ERROR_END_OF_STREAM

[More messages about function not implemented]

**Comment by xpzz** [comment]
should this issue reopened? :P

**Comment by frapeti** [comment]
It seems like it's the cause of lwp not working without msaa

**Comment by xpzz** [comment]
@frapeti  @diego-ch  after last nightly where frapati reverted the lwp fix  videos are working fine....

**Comment by xpzz** [comment]
Sorry it doesn't fixed yet...  a lot of videos still not working properly... if you open youtube by browser videos doesn't work... small videos that you recieve by whatsapp (3gp, mp4, avi) you can't view in full screen... appears a black screen and only audio is reproduced...

**Comment by xpzz** [comment]
@frapeti  this issue was confirmed as rom issue on SIII mini.. this should be reopened or no?

PS: Oliver made a code to an workaround that fix it...

http://forum.xda-developers.com/showpost.php?p=45829979&postcount=521

**Comment by diego-ch** [comment]
@OliverG96, was that fix pushed to our framework repo?

2013/9/25 xpzz notifications@github.com

> @frapeti https://github.com/frapeti this issue was confirmed as rom
> issue on SIII mini.. this should be reopened no?
> 
> PS: Oliver made a code to an workaround that fix it...
> 
> http://forum.xda-developers.com/showpost.php?p=45829979&postcount=521
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCanjica/TeamCanjica/issues/2#issuecomment-25062120
> .

## 

Diego Porto
Graduando em Ciência da Computação - UFPB
