### ISSUE TITLE
Wi-Fi stuck/Wi-Fi tethering

### ISSUE THREAD

**Issue by abcjanice** [TeamCanjica/TeamCanjica#20]
When i try to turn on the Wi-Fi, it gets stuck for 10-20 seconds and then unlocks without problem. Sometimes Wi-Fi gets stuck for a long period time (about 1 minute or more) and doesn't turn on. This issue affects (not always) the tethering too: sometimes it doesn't turn on or gets stuck like Wi-Fi. It's a really annoying issue.

**Comment by frapeti** [comment]
Do a clean flash with all wipes of the last nightly, if it persists tell us how to replicate in original xda thread and it could be reopened
