### ISSUE TITLE
i9070 - CM 10.2 Touch screen does not work after reboot

### ISSUE THREAD

**Issue by avin45h** [TeamCanjica/TeamCanjica#29]
Case : Touch screen does not work
Happens when : after reboot (at random, works fine mostly)
How to fix : reboot (reboot till it starts working, might need to restart more than 2-3 times)

Points : it does not happen since start, after reboot touch will work always, but suddenly the touch screen will fail to work.

**Comment by diego-ch** [comment]
known issue,
we're looking into it, but it's not top priority

2013/11/30 Avinash Verma notifications@github.com

> Case : Touch screen does not work
> Happens when : after reboot (at random, works fine mostly)
> How to fix : reboot (reboot till it starts working, might need to restart
> more than 2-3 times)
> 
> Points : it does not happen since start, after reboot touch will work
> always, but suddenly the touch screen will fail to work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCanjica/TeamCanjica/issues/29
> .

## 

Diego Porto
Graduando em Ciência da Computação - UFPB

**Comment by chamoo2000** [comment]
Same problem ... here ... i have GT-i9070 Running CM 10.2

when it happens first 2 restarts fixed it .. then it happens again and i restarted 5 times but still not working , so i factory reset it-(Wipe Data) from CW Mod and it fixed it ... but it continues ... plz fix this...... i like this ROM very much... :(

**Comment by diego-ch** [comment]
cocafe is working on that issue :)

2013/12/18 chamoo2000 notifications@github.com

> Same problem ... here ... i have GT-i9070 Running CM 10.2
> 
> when it happens first 2 restarts fixed it .. then it happens again and i
> restarted 5 times but still not working , so i factory reset it-(Wipe Data)
> from CW Mod and it fixed it ... but it continues ... plz fix this...... i
> like this ROM very much... :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCanjica/TeamCanjica/issues/29#issuecomment-30823712
> .

## 

Diego Porto
Graduando em Ciência da Computação - UFPB

**Comment by rengow** [comment]
To fix that, force reboot and then use it for a minutes. That work for me :)

**Comment by gongol1970** [comment]
I have the same issue in the JB stock rom for Argentina.
