### ISSUE TITLE
low call volume on headphone

### ISSUE THREAD

**Issue by avin45h** [TeamCanjica/TeamCanjica#35]
Problem : Low call volume in headphones, normal song playback is really good, but whenever it's a call, the call volume wont be as loud as the song is when it plays.

Tried many headsets/headphones, all yield same result. Songs play awesome, but in call volume is too low compared to the songs. Can this be boosted?

**Comment by ghost** [comment]
There are many thrid-party apps to do this. Low INCall volumes should be fine anyway. Which ROM is this on?
