### ISSUE TITLE
CM11 2014-02-09 janice - Upload/Download arrows on Data connection

### ISSUE THREAD

**Issue by slavosarik** [TeamCanjica/TeamCanjica#37]
Upload/Download arrows on Data connection (edge/3g) are not working. Arrows are working on wifi connection.

**Comment by sudwind** [comment]
That's the way they are supposed to work. They only show on quick settings.

**Comment by slavosarik** [comment]
Arrows on data connection were working properly on CM 10.1, since CM10.2 they are not working. Even Rox has mentioned in his Ace2 thread that arrows are not working.

Edit: I was talking about arrow indicator in status bar, it does not signal whether data are being sent/received.

**Comment by RobertRozic** [comment]
Fixed with new kernel
