### ISSUE TITLE
GT-I9070 | Mail not working

### ISSUE THREAD

**Issue by ingratonombre** [TeamCanjica/TeamCanjica#39]
Hi, i had Omni 4.3 version 4.3.1-20131218-janice-HOMEMADE. I tried to add mail accounts (exchange, outlook) and not work. Never syncronize. I need help. Thanks

**Comment by sudwind** [comment]
Omni 4.3 is now deprecated. we are moving to 4.4 soon. And anyway, Omni 4.3 was never fully finished, because it went out near the Android 4.4 release date and all development from the official OmniROM resumed on 4.4.
