### ISSUE TITLE
[i9070/CM10.1/N27/08/13] Phone stucks on Low power mode and sometimes don't charge

### ISSUE THREAD

**Issue by xpzz** [TeamCanjica/TeamCanjica#4]
when you got a completly empty battery and put phone to charge it stuck on boot like an  "preparing to charge"  in most cases it charges the battery after some time... but with me one time it can't happened and to revive my phone I had to charge the battery in another phone withou CM10.1

**Comment by frapeti** [comment]
it's fixed now ;)
