### ISSUE TITLE
[i9070/CM10.1/N27/08/13] Volume during calls changes if switching to the speaker and viceversa

### ISSUE THREAD

**Issue by vicodin99** [TeamCanjica/TeamCanjica#5]
When making a call, the earpiece's volume is just fine. When you switch to the speaker, volume is quite low. It can be solved pressing volume down then volume up until you are satisfied with it. When going back to the earpiece, same volume issue, same solution.

**Comment by gongol1970** [comment]
I have the same issue, the volume is allways low, I need to down and up the volume and then got the original volume setted up (high).
