### ISSUE TITLE
[i9070/CM10.1/N27/08/13] Interface laggy/not smooth unless Mali settings are configured to their maximum allowed options

### ISSUE THREAD

**Issue by vicodin99** [TeamCanjica/TeamCanjica#6]
Settings -> Advanced -> Advanced -> GPU

Mali L2 Max Reads: 48kb (already at its highest by default)
Mali Pre-allocated memory size: should be set to 48MB, comes by default at 16 or 24mb, can't remember

When set to 48mb the interface becomes buttery smooth. Maybe this setting can be changed to 48mb by default in next builds?

**Comment by frapeti** [comment]
yes, I'll try to fix it

**Comment by frapeti** [comment]
it should be fixed now
