### ISSUE TITLE
I9070/CM 10.1/n27/08/13 there is a thelephonic number imposted in segretery

### ISSUE THREAD

**Issue by crisfrullo** [TeamCanjica/TeamCanjica#7]
In segretery deviation there are 3 number of Phone  +39.....and when You want to delete it for typing a correct number for the deviation, You can't do that and a pop up appear to segnale that there is an error on the telephonic operator.

**Comment by frapeti** [comment]
Sorry I don't understand, can you explain it better?

**Comment by crisfrullo** [comment]
Scusa per il mio inglese ma sono ormai 30 anni che non lo parlo, il
problema è questo, se devi attivare le deviazioni di chiamata per la
segreteria telefonica devi impostare il numero telefonico al quale deviare,
nel telefono invece sono impostati di default un +3945113 che non riesci a
cambiare e la risposta  che appare  sul telefono dopo aver modificato il
numero e lanciato la richiesta  è che il telefono non può fare la richiesta
in quanto il telefono è già  in uso oppure che c'è un problema sulla SIM o
sulla rete nel mio caso Vodafone.. Non riesci quindi a far fare le
deviazioni quando occupato - senza copertura oppure non vuoi rispondere. Un
ringraziamento comunque per la splendida ROM che fa rivivere il telefono.
Bravi e continuate così. Ciao
Il giorno 29/ago/2013 05:56, "Franco Rapetti" notifications@github.com ha
scritto:

**Comment by frapeti** [comment]
it's working fine here, and if it doesn't work for you it's related to your service provider instead of a rom bug, next time use Google translate 8)
