### ISSUE TITLE
[i9070/CM10.1/N27/08/13] Live wallpapers don't work unless 4x MSAA is forced at developer settings

### ISSUE THREAD

**Issue by vicodin99** [TeamCanjica/TeamCanjica#8]
When that setting is forced, live wallpapers work.

Is this because they require MSAA to look good, as a necessary thing to run? I mean, you don't want a wallpaper which is full of jaggies... But that forced setting, if I'm right is global, and other applications like games would have a big performance hit because of the extra processing.

Is there a way to enable MSAA only for the wallpapers? Or maybe there's another workaround...

**Comment by frapeti** [comment]
I didnt see any decreased performance caused by forcing msaa, try some 3D benchmarking apps to compare it

**Comment by frapeti** [comment]
it will be reopen if necessary, when someone prove that it worth it

**Comment by frapeti** [comment]
its fixed now
