### ISSUE TITLE
Low volume in calls

### ISSUE THREAD

**Issue by frapeti** [TeamCanjica/TeamCanjica#9]
You need to press vol- and vol+ to make it normal

**Comment by ar-lex** [comment]
I don't have this bug in my recent builds of cm-10.1 for codina. Didn't make any changes to the sources.

**Comment by frapeti** [comment]
It's for incoming calls only

**Comment by diego-ch** [comment]
I don't have this issue on janice with DDULP8 baseband.
build 2013 09 19

2013/9/22 Franco Rapetti notifications@github.com

> It's for incoming calls only
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCanjica/TeamCanjica/issues/9#issuecomment-24887522
> .

## 

Diego Porto
Graduando em Ciência da Computação - UFPB

**Comment by frapeti** [comment]
Nice you sure? I can't test it anymore cause of my imei issue :p

**Comment by ar-lex** [comment]
I don't see the difference between the volume of out- and incoming calls... It was much lower on cm-10 and now it seems unusually high:)

**Comment by diego-ch** [comment]
same here. it works as it should.

2013/9/23 ar-lex notifications@github.com

> I don't see the difference between the volume of out- and incoming
> calls... It was much lower on cm-10 and now it seems unusually high:)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TeamCanjica/TeamCanjica/issues/9#issuecomment-24938931
> .

## 

Diego Porto
Graduando em Ciência da Computação - UFPB

**Comment by frapeti** [comment]
I will reopen it if necessary

**Comment by gongol1970** [comment]
I have this issue, with CM10.1 and now with CM10.2
